services:
  - type: web
    name: nova-chatbot
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: APP_NAME
        value: Nova Chatbot
      - key: MODEL
        value: llama3-8b-8192
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_MIN
        value: 30
      - key: REFRESH_EXPIRES_DAYS
        value: 14
